### ISSUE TITLE
Font size is to small on Chrome

### ISSUE THREAD

**Issue by godhandkiller** [mallowigi/material-dev-tools#9]
![Screen Shot 2019-12-02 at 16 38 44](https://user-images.githubusercontent.com/18409311/70001275-7e48e800-1522-11ea-981d-a1fb62f28a82.png)
![Screen Shot 2019-12-02 at 16 38 28](https://user-images.githubusercontent.com/18409311/70001282-8143d880-1522-11ea-8281-19fb045f58a5.png)

So the font on chrome dev tools is way to small, I have it on 22px on my settings but it looks like it's not changing

**Comment by spaghett1c0de** [comment]
@mallowigi I'm having the same issue. The font size doesn't seem to be updating.

**Comment by mallowigi** [comment]
fixed in 2.7

**Comment by saltdotac** [comment]
Still seeing in 2.7. Appears to only reflect font size in "sources" panel.

**Comment by mallowigi** [comment]
fixed for 3.1
